# The URL the site will be built for
base_url = "https://CSUwangj.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
title = "LuckyDog | CSUwangj's Blog"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
theme = "DogFood"
generate_feed = true
feed_filename = "atom.xml"
taxonomies = [
  {name = "categories", rss = true},
  {name = "tags", rss = true},
  {name = "archives", rss = true},
]


[extra]
site_name = "LuckyDog"
menu_items = [
  {url = "$BASE_URL", name = "Home", icon = "fa fa-home"},
  {url = "$BASE_URL/about", name = "About", icon = "fa fa-user-circle-o"},
  {url = "$BASE_URL/categories", name = "Categories", icon = "fa fa-book"},
  {url = "$BASE_URL/tags", name = "Tags", icon = "fa fa-tags"},
  {url = "$BASE_URL/archives", name = "Archives", icon = "fa fa-inbox"},
]
author = "CSUwangj"
quote = "Just keep in mind that hacking is very rarely in a sequence."
links = [
  {name = "领路人JDchen学长", url = "http://www.cnblogs.com/0xJDchen/"},
  {name = "吉祥物", url = "https://www.cnblogs.com/0xHack/"},
  {name = "社会我王哥", url = "https://wangyx-max.github.io/"},
  {name = "WolfBolin", url = "https://wolfbolin.com/"},
  {name = "bocity", url = "https://haolovej.com/"},
  {name = "长门有希", url = "https://blog.yuki-nagato.com/"},
  {name = "郁离歌", url = "http://yulige.top/"},
  {name = "Error404", url = "https://www.jianshu.com/u/fa23d591f030"},
  {name = "王一航", url = "https://www.jianshu.com/u/bf30f18c872c"},
  {name = "伍尚国", url = "http://www.cnblogs.com/wushangguo/"},
  {name = "Porlockz", url = "http://www.porlockz.com/"},
  {name = "黄含绦", url = "https://huanghantao.github.io/"},
  {name = "ZickShen", url = "https://zickshen.github.io/"},
]
author_links = [
  {name = "Github", url = "https://github.com/CSUwangj", favion = "fa fw fa-github"},
  {name = "EMail", url = "mailto:CSUwangj@protonmail.com", favion = "fa fw fa-envelope"},
]
copyright_year = "2018-2020"
avatar = "img/avatar.png"
