# The URL the site will be built for
base_url = "https://CSUwangj.github.io/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
title = "LuckyDog | CSUwangj's Blog"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false
theme = "DogFood"
generate_feed = true
feed_filename = "atom.xml"
taxonomies = [
  {name = "categories", feed = true},
  {name = "tags", feed = true},
  {name = "archives", feed = true},
]

[markdown]
external_links_target_blank = true
external_links_no_referrer = true
external_links_no_follow = true

[link_checker]
internal_level = "warn"

[slugify]
taxonomies = "off"

[extra]
site_name = "LuckyDog"
menu_items = [
  {url = "$BASE_URL", name = "Home", icon = "fa-solid fa-house"},
  {url = "$BASE_URLabout", name = "About", icon = "fa-solid fa-user-circle"},
  {url = "$BASE_URLcategories", name = "Categories", icon = "fa-solid fa-book"},
  {url = "$BASE_URLtags", name = "Tags", icon = "fa-solid fa-tags"},
  {url = "$BASE_URLarchives", name = "Archives", icon = "fa-solid fa-inbox"},
  {url = "$BASE_URLZDaily", name = "DailyChallenge", icon = "fa-solid fa-calendar-check"},
  {url = "$BASE_URLWebtools", name = "Webtools", icon = "fa-solid fa-toolbox"},
]
author = "CSUwangj"
quote = "Just keep in mind that hacking is very rarely in a sequence."
links = [
  {name = "WolfBolin", url = "https://wolfbolin.com/"},
  {name = "长门有希", url = "https://blog.yuki-nagato.com/"},
  {name = "Porlockz", url = "http://www.porlockz.com/"},
  {name = "Phosphorus", url = "https://way.lu/"},
  {name = "Edwardzcn", url = "https://edwardzcn.github.io/"},
  {name = "吕少", url = "https://www.cnblogs.com/csu-lmw/"},
  {name = "ZickShen", url = "https://zickshen.github.io/"},
]
author_links = [
  {name = "Github", url = "https://github.com/CSUwangj", favion = "fa-brands fa-github"},
  {name = "EMail", url = "mailto:CSUwangj@protonmail.com", favion = "fa-solid fa-envelope"},
]
copyright_year = "2018-2022"
avatar = "images/avatar.png"
katex_enabled = true