# The URL the site will be built for
base_url = "https://CSUwangj.github.io/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
title = "LuckyDog | CSUwangj's Blog"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false
theme = "DogFood"
generate_feed = true
feed_filename = "atom.xml"
taxonomies = [
  {name = "categories", rss = true},
  {name = "tags", rss = true},
  {name = "archives", rss = true},
]

[slugify]
taxonomies = "off"


[extra]
site_name = "LuckyDog"
menu_items = [
  {url = "$BASE_URL", name = "Home", icon = "fa fa-home"},
  {url = "$BASE_URLabout", name = "About", icon = "fa fa-user-circle-o"},
  {url = "$BASE_URLcategories", name = "Categories", icon = "fa fa-book"},
  {url = "$BASE_URLtags", name = "Tags", icon = "fa fa-tags"},
  {url = "$BASE_URLarchives", name = "Archives", icon = "fa fa-inbox"},
  {url = "$BASE_URLZDaily/", name = "DailyChallenge", icon = "fa fa-calendar-check-o"},
]
author = "CSUwangj"
quote = "Just keep in mind that hacking is very rarely in a sequence."
links = [
  {name = "WolfBolin", url = "https://wolfbolin.com/"},
  {name = "bocity", url = "https://haolovej.com/"},
  {name = "长门有希", url = "https://blog.yuki-nagato.com/"},
  {name = "Porlockz", url = "http://www.porlockz.com/"},
  {name = "松鼠", url = "https://sosusosu.icu/"},
  {name = "ZickShen", url = "https://zickshen.github.io/"},
]
author_links = [
  {name = "Github", url = "https://github.com/CSUwangj", favion = "fa fw fa-github"},
  {name = "EMail", url = "mailto:CSUwangj@protonmail.com", favion = "fa fw fa-envelope"},
]
copyright_year = "2018-2021"
avatar = "img/avatar.png"
katex_enabled = true